### ISSUE TITLE
Python InValid Version  - Wrong error message

### ISSUE THREAD

**Issue by sgokaram-saagie** [saagie/gradle-saagie-dataops-plugin#168]
updating a job with a wrong python version ( eg: 2.9) the error message is not ambigous. 

saagies-mbp:Gradle shivakumar$ gradle -b build.gradle.projectsUpdateJob projectsUpdateJob

> Task :projectsUpdateJob FAILED
Something went wrong when adding new job version: {"errors":[{"message":"Job version invalid","extensions":{"version":"not exists","classification":"ValidationError"}}],"data":null}

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':projectsUpdateJob'.
> Something went wrong when adding new job version: {"errors":[{"message":"Job version invalid","extensions":{"version":"not exists","classification":"ValidationError"}}],"data":null}

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
1 actionable task: 1 executed

The error message has Job version invalid but its indeed Python version invalid or should atleast say technology version invalid.

**Comment by DecampsRenan** [comment]
The response you see come from the API:
![image](https://user-images.githubusercontent.com/7521065/75865015-2791c980-5e03-11ea-84f1-8d11d7bc0cdb.png)

We can add this kind of personalized message, but we will need to do that on **all possible errors** for the rest of the project, and it imply a lot more work and you have to keep in mind that if the error message / key change API side, we need to update it on the plugin side

If we do that, we will need a list of all possible errors.
It's more efficient to update the error message from the API side.

**Comment by sgokaram-saagie** [comment]
We will fix the API and we dont want to do any special handling in Plugin. Thats too much work.
