### ISSUE TITLE
projectCreatePipeline Error

### ISSUE THREAD

**Issue by sgokaram-saagie** [saagie/gradle-saagie-dataops-plugin#170]
Gradle File 

plugins {
  id "io.saagie.gradle-saagie-dataops-plugin" version "1.1.70"
}

saagie {
    server {
        url = saagieurl
        login = saagieuserid
        password = saagiepassword
        environment = saagieplatformid
        jwt = true
    }
    project {
        id = saagieprojectid
    }

    pipeline {
          name = "Testing Pipeline with Gradle 1.1.70"
          description = "my description"
          isScheduled = false
          alerting {
            emails=['Shivakumar.gokaram@saagie.com']
            statusList= ['FAILED','KILLED','KILLING']
          }
        }

    pipelineVersion {
      releaseNote = "Notes"
      jobs = [ "4bae9edb-61f9-4187-a5b2-7fca96c7db78"]
    }
}

Error
saagies-mbp:Gradle shivakumar$ gradle -b build.gradle.projectCreatePipeline projectCreatePipeline

> Task :projectsCreatePipeline FAILED
Something went wrong when creating the pipeline: {"errors":[{"message":"Pipeline not valid","extensions":{"pipeline":"not allowed","classification":"ValidationError"}}],"data":null}

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':projectsCreatePipeline'.
> Something went wrong when creating the pipeline: {"errors":[{"message":"Pipeline not valid","extensions":{"pipeline":"not allowed","classification":"ValidationError"}}],"data":null}

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
1 actionable task: 1 executed

**Comment by DecampsRenan** [comment]
It seems the saagie API do not allow creating a pipeline with only one job; I saw this when testing creating a pipeline from the saagie UI

You need at least two jobs to create a valid pipeline

Response received from the API (the one you see in the plugin):
![image](https://user-images.githubusercontent.com/7521065/75863085-362ab180-5e00-11ea-8ea9-0999934bd9d1.png)

Validation error message from the Saagie UI:
![image](https://user-images.githubusercontent.com/7521065/75863011-18f5e300-5e00-11ea-97a8-7dc3c7fb53b3.png)

**Comment by sgokaram-saagie** [comment]
I was able to create if i provide more than one job.
