### ISSUE TITLE
ProjectListTechnology - Docker 

### ISSUE THREAD

**Issue by sgokaram-saagie** [saagie/gradle-saagie-dataops-plugin#188]
The output of ListTechnology for Docker seems a bit odd.  Why is the API returning SCHEDULER for docker technology. 

[
 
  {
    "id": "39510510-7262-459d-83c2-8e5d2e8bbdd8",
    "label": "Docker",
    "isAvailable": true,
    "icon": "docker",
    "features": [
      {
        "field": "DOCKER_INFO",
        "label": "Docker image",
        "isMandatory": true,
        "comment": null,
        "defaultValue": "hello-world"
      },
      {
        "field": "SCHEDULER",
        "label": "Scheduled",
        "isMandatory": true,
        "comment": null,
        "defaultValue": null
      }
    ]
  }
]

**Comment by medamineziraoui** [comment]
I find it odd too but This is the output of the api, and we have no control over it

**Comment by sgokaram-saagie** [comment]
ok. we will have to fix the API.
