### ISSUE TITLE
projectExport - overwrite file option is not honored

### ISSUE THREAD

**Issue by sgokaram-saagie** [saagie/gradle-saagie-dataops-plugin#200]
projectExport does not seem to check if the file exists and just over writes it irrespective of the overwrite value. 

To simulate run the below twice , the first time should work the next time it should fail as the file exists. 

plugins {
  id "io.saagie.gradle-saagie-dataops-plugin" version "1.1.79"
}

saagie {
    server {
        url = saagieurl
        login = saagieuserid
        password = saagiepassword
        environment = saagieplatformid
        jwt = true
    }
    project {
        id = saagieprojectid
    }
    job {
          ids = [ "2044dab3-5c3a-4985-8fa9-622e43fede52","d403e701-3d0d-42d5-b000-0c4a5bc4b8d2" ]
        }
    exportArtifacts {
          export_file = "./job/export.zip"
          overwrite=false
          temporary_directory='./tmp'
    }
}

**Comment by sgokaram-saagie** [comment]
This is a expected behaviour as if the same name is found it will create a new version of the job.

**Comment by medamineziraoui** [comment]
- [ ] Changed behavior if file exist and overwrite option is false to throw error
- [ ] Tested Localy
- [ ] Tested release
