### ISSUE TITLE
Gradle tasks

### ISSUE THREAD

**Issue by sgokaram-saagie** [saagie/gradle-saagie-dataops-plugin#218]
Saagie tasks
------------
groupList - List all groups for the user
platformList - List available platforms
projectsCreate - Create a brand new project
projectsCreateJob - Create a brand new job in a project
projectsCreatePipeline - Create a pipeline
projectsDelete - Archive a project
projectsDeleteJob - Delete a job
projectsDeletePipeline - delete a pipeline
projectsExport - Export a list of jobs or pipelines for a project to a zip extension
projectsExportV1 - Export a list of jobs or pipelines from REST for a project to a zip extension
projectsGetJobInstanceStatus - Get the status of a job instance
projectsGetPipelineInstanceStatus - Get the status of a pipeline instance
projectsImport - Import a List of jobs or pipelines using the artifacts from a zip location
projectsList - List all projects on the environment
projectsListJobs - List all jobs of a project
projectsListPipelines - List all pipelines of a project
projectsListTechnologies - List all technologies of a project
projectsRunJob - Run an existing job
projectsRunPipeline - Run a pipeline
projectsStopJobInstance - Stop a job instance
projectsStopPipelineInstance - Stop a pipeline instance
projectsUpdate - Update an existing project
projectsUpgradeJob - Upgrade a existing job in a project
projectsUpgradePipeline - Upgrade a pipeline
technologyList - List all technologies for the user

Change the description for ExportV1 
Export a list of jobs or pipelines from Manager to a zip format to be imported into V2( projects).

**Comment by medamineziraoui** [comment]
- Changed description for projectsExportV1
Export a list of jobs or pipelines from Manager to a zip format to be imported into V2( projects).

Release fixe : 2.0.9

**Comment by medamineziraoui** [comment]
**How to test :**

Version to test : **2.0.20**
show description of the saagie 
Export job using this commande :
**The command line** : `gradle tasks`

**Bug behvior**
```
groupList - List all groups for the user
platformList - List available platforms
projectsCreate - Create a brand new project
projectsCreateJob - Create a brand new job in a project
projectsCreatePipeline - Create a pipeline
projectsDelete - Archive a project
projectsDeleteJob - Delete a job
projectsDeletePipeline - delete a pipeline
projectsExport - Export a list of jobs or pipelines for a project to a zip extension
projectsExportV1 - Export a list of jobs or pipelines from REST for a project to a zip extension
projectsGetJobInstanceStatus - Get the status of a job instance
projectsGetPipelineInstanceStatus - Get the status of a pipeline instance
projectsImport - Import a List of jobs or pipelines using the artifacts from a zip location
projectsList - List all projects on the environment
projectsListJobs - List all jobs of a project
projectsListPipelines - List all pipelines of a project
projectsListTechnologies - List all technologies of a project
projectsRunJob - Run an existing job
projectsRunPipeline - Run a pipeline
projectsStopJobInstance - Stop a job instance
projectsStopPipelineInstance - Stop a pipeline instance
projectsUpdate - Update an existing project
projectsUpgradeJob - Upgrade a existing job in a project
projectsUpgradePipeline - Upgrade a pipeline
technologyList - List all technologies for the user
```

**Expected behvior**
```
Saagie tasks
------------
groupList - List all groups for the user
platformList - List available platforms
projectExportJob1 - export v1 job for saagie
projectExportJob2 - export v1 job for saagie
projectsCreate - Create a brand new project
projectsCreateJob - Create a brand new job in a project
projectsCreatePipeline - Create a pipeline
projectsDelete - Archive a project
projectsDeleteJob - Delete a job
projectsDeletePipeline - delete a pipeline
projectsExport - Export a list of jobs or pipelines for a project to a zip extension
projectsExportV1 - Export a list of jobs or pipelines from Manager to a zip format to be imported into V2( projects)
projectsGetJobInstanceStatus - Get the status of a job instance
projectsGetPipelineInstanceStatus - Get the status of a pipeline instance
projectsImport - Import a List of jobs or pipelines using the artifacts from a zip location
projectsList - List all projects on the environment
projectsListJobs - List all jobs of a project
projectsListPipelines - List all pipelines of a project
projectsListTechnologies - List all technologies of a project
projectsRunJob - Run an existing job
projectsRunPipeline - Run a pipeline
projectsStopJobInstance - Stop a job instance
projectsStopPipelineInstance - Stop a pipeline instance
projectsUpdate - Update an existing project
projectsUpgradeJob - Upgrade a existing job in a project
projectsUpgradePipeline - Upgrade a pipeline
technologyList - List all technologies for the user
```
