### ISSUE TITLE
Error importing Java/Scala Job

### ISSUE THREAD

**Issue by sgokaram-saagie** [saagie/gradle-saagie-dataops-plugin#220]
Unable to import the Java/Scala Job.  Export works fine. 
Job id is 21754

shivakumar@saagies-mbp Gradle % gradle -b build.gradle.projectExportJobV1 projectExportV1

> Task :projectsExportV1
{"status":"success","exportfile":"./job/export.zip"}

BUILD SUCCESSFUL in 19s
1 actionable task: 1 executed
shivakumar@saagies-mbp Gradle % gradle -b build.gradle.projectImportJob projectImport

> Task :projectsImport FAILED
Something went wrong when creating project job: {"errors":[{"message":"Job not valid","extensions":{"commandLine":"not allowed","package":"not allowed","classification":"ValidationError"}}],"data":null}

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':projectsImport'.
> Something went wrong when creating project job: {"errors":[{"message":"Job not valid","extensions":{"commandLine":"not allowed","package":"not allowed","classification":"ValidationError"}}],"data":null}

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s
1 actionable task: 1 executed

plugins {
  id "io.saagie.gradle-saagie-dataops-plugin" version "2.0.8"
}

saagie {
    server {
        url = saagieurl
        login = saagieuserid
	password = saagiepassword
        environment = saagieplatformid
	jwt = true
    }
    job {
          ids =  [ "21754" ]
        }
    exportArtifacts {
          export_file = "./job/export.zip"
          overwrite=true
	  temporary_directory='./tmp'
    }
}

**Comment by medamineziraoui** [comment]
- [x] some of the job of type "Java/scala" doesn t succeed at export du to runtimeVersion mapping error
- [x] Fixed mapping for the  Java/scala export 
- [x] tested export and import for "Java/scala"

**Comment by medamineziraoui** [comment]
Need validation for this issue @sgokaram-saagie

**Comment by medamineziraoui** [comment]
**How to test :**

Version to test : **2.0.20**

**The Export phase:**
Create a build file:
**Example of** `build.projectsExportV1.gradle`:

```
plugins {
  id "io.saagie.gradle-saagie-dataops-plugin" version "2.0.20"
}
saagie {
    server {
        url = "REPLACE_SAAGIEURL"
        login = "REPLACE_SAAGIELOGIN"
	password = "REPLACE_SAAGIEPASSWORD"
        environment = "REPLACE_SAAGIE"
	jwt = true
    }
    job {
          ids =  [ "21754" ]
        }
    exportArtifacts {
          export_file = "./job/export.zip" // <=== url "./job/" should exist  
          overwrite=true
	  temporary_directory='./tmp'    // <=== temporary_directory ./tmp'  should exist        
    }
}
```

Export job using this commande :
**The command line** : `gradle -b build.projectsExportV1.gradle projectsExportV1`

**The import phase:** 

Create a new build file:
**Example :** build.projectsImport.gradle:

```
plugins {
    id 'groovy'
    id 'io.saagie.gradle-saagie-dataops-plugin' version '2.0.15'
}

saagie {
    server {
        url = "REPLACE_SAAGIEURL"
        login = "REPLACE_SAAGIELOGIN"
	password = "REPLACE_SAAGIEPASSWORD"
        environment = "REPLACE_SAAGIE"
	jwt = true
        acceptSelfSigned = true
    }
    project {
        id = "REPLACE_SAAGIE_PROJECT_ID"
    }
    importArtifacts {
        import_file = "./job/export.zip"
        temporary_directory='./tmp'
    }
}
```
Then use this command line:
**The command line :** `gradle -b build.projectsImport.gradle projectsImport`
Old behavior:
You should get
```
Task :projectsImport FAILED
Something went wrong when creating project job: {"errors":[{"message":"Job not valid","extensions":{"commandLine":"not allowed","package":"not allowed","classification":"ValidationError"}}],"data":null}
```
