### ISSUE TITLE
Error importing pipeline from V1 

### ISSUE THREAD

**Issue by sgokaram-saagie** [saagie/gradle-saagie-dataops-plugin#232]
Exported pipeline 
plugins {
  id "io.saagie.gradle-saagie-dataops-plugin" version "2.0.17"
}

saagie {
    server {
        url = saagieurl
        login = saagieuserid
	password = saagiepassword
        environment = saagieplatformid
	jwt = true
    }
    pipeline {
          ids = [ "486" ]
          include_job=true
        }
    exportArtifacts {
          export_file = "./pipeline/486.zip"
          overwrite=true
	  temporary_directory = "./tmp/"
    }
}

Export was successful. 
Tried importing this pipeline but failed. 

plugins {
  id "io.saagie.gradle-saagie-dataops-plugin" version "2.0.17"
}

saagie {
    server {
        url = saagieurl
        login = saagieuserid
	password = saagiepassword
        environment = saagieplatformid
	jwt = true
    }
    project {
        id = saagieprojectid
    }

    importArtifacts {
        import_file = "./pipeline/486.zip"
    }
}

shivakumar@saagies-mbp Gradle % gradle -b build.gradle.projectImportPipeline projectImport
To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/6.5/userguide/gradle_daemon.html.
Daemon will be stopped at the end of the build stopping after processing

> Task :projectsImport
Directory created successfully
Something went wrong when creating project job: {"errors":[{"message":"Job not valid","extensions":{"version":"not exists","classification":"ValidationError"}}],"data":null}

> Task :projectsImport FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':projectsImport'.
> Something went wrong when creating project job: {"errors":[{"message":"Job not valid","extensions":{"version":"not exists","classification":"ValidationError"}}],"data":null}

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s
1 actionable task: 1 executed

**Comment by medamineziraoui** [comment]
Found bug source in generation of json file while exporting
 Fixing the wrong mapping
 tested with pipeline 331 localy

**Comment by medamineziraoui** [comment]
**How to test :**

Version to test : **2.0.20**

**The Export phase:**

We going to call this process Export/Import-job

Create a build file:
**Example of** `build.projectsExportV1.gradle`:

```
plugins {
  id "io.saagie.gradle-saagie-dataops-plugin" version "2.0.22"
}
saagie {
    server {
        url = "REPLACE_SAAGIEURL"
        login = "REPLACE_SAAGIELOGIN"
	password = "REPLACE_SAAGIEPASSWORD"
        environment = "REPLACE_SAAGIE"
	jwt = true
    }
    pipeline {
          ids = [ "486" ]
        include_job=true
    }
     exportArtifacts {
          export_file = "./pipeline/486.zip"
	  temporary_directory='./tmp'    // <=== temporary_directory ./tmp'  should exist        
    }
}
```
Export job using this commande :
**The command line** : `gradle -b build.projectsExportV1.gradle projectsExportV1`

**The import phase:** 
```
plugins {
    id 'groovy'
    id 'io.saagie.gradle-saagie-dataops-plugin' version '2.0.22'
}

saagie {
    server {
        url = saagieurl
        login = saagieuserid
        password = saagiepassword
        environment = saagieplatformid
        jwt = true
        acceptSelfSigned = true
    }

    project {
        id = saagieProject
    }

    importArtifacts {
        import_file = "./pipeline/486.zip"
          temporary_directory='./tmp'
    }
}
```

** Bug behavior **
```
FAILURE: Build failed with an exception.

What went wrong:
Execution failed for task ':projectsImport'.
Something went wrong when creating project job: {"errors":[{"message":"Job not valid","extensions":{"version":"not exists","classification":"ValidationError"}}],"data":null}


```
** Expected behavior **
```
> Task :projectsImport
{status=success, job=[{id=2779, name=ERP Data Cleansing}, {id=2778, name=Import ERP Data}, {id=9726, name=Build model (sales / ERP)}], pipeline=[{id=486, name=My datapipeline}]}

BUILD SUCCESSFUL in 9s
1 actionable task: 1 executed
```
