### ISSUE TITLE
ProjectImport - Data is not cleaned up

### ISSUE THREAD

**Issue by sgokaram-saagie** [saagie/gradle-saagie-dataops-plugin#239]
Looks like for project import the export directory is used as working directory and also the files are not cleaned up. 
The file i exported was 486.zip. But after import i see a directory as 486 and also the rest of the files. If you need temporary directory then we need to add that option into the import configuration and also ensure to clean it up. 

saagies-mbp:pipeline shivakumar$ ls -tlar
total 32
-rw-r--r--@  1 shivakumar  staff  6148 Jun 23 13:12 .DS_Store
-rw-r--r--   1 shivakumar  staff     0 Jun 29 10:18 .!76312!.DS_Store
-rw-r--r--   1 shivakumar  staff     0 Jun 29 10:18 .!76313!486.zip
drwxrwxr-x@  6 shivakumar  staff   192 Jun 29 10:18 486
drwxr-xr-x   7 shivakumar  staff   224 Jun 29 10:22 .
-rw-r--r--   1 shivakumar  staff  5926 Jun 29 10:22 486.zip
drwxr-xr-x  53 shivakumar  staff  1696 Jun 29 10:22 ..

**Comment by medamineziraoui** [comment]
**How to test :**
We going to call this process Export/Import-job
Export job using this commande :
`gradle -b build.gradle projectsExportV1`


```
plugins {
  id "io.saagie.gradle-saagie-dataops-plugin" version "2.0.15"
}
saagie {
    server {
        url = saagieurl
        login = saagieuserid
	password = saagiepassword
        environment = saagieplatformid
	jwt = true
    }
    job {
          ids =  [ "21754" ]
        }
    exportArtifacts {
          export_file = "./job/export.zip" // <=== url "./job/" should exist  
          overwrite=true
	  temporary_directory='./tmp'    // <=== temporary_directory ./tmp'  should exist        
    }
}
```
You should get
{"status":"success","exportfile":"./job/export.zip"}
Then use this command to export the job V1

`gradle -b build.gradle ProjectsImport`

```
plugins {
    id 'groovy'
    id 'io.saagie.gradle-saagie-dataops-plugin' version '2.0.15'
}

saagie {
    server {
        url = saagieurl
        login = saagieuserid
        password = saagiepassword
        environment = saagieplatformid
        jwt = true
        acceptSelfSigned = true
    }
    project {
        id = saagieProject
    }
    importArtifacts {
        import_file = "./job/export.zip"
        temporary_directory='./tmp'
    }
}
```
Repeat the Export/Import-job process but this time remove the ` temporary_directory='./tmp'` from `importArtifacts` in the `projectsImport` task, what happens now the task will use the `tmp` folder of the system so check if there is any folder added and not removed after the task is finished

**Expected behvior**
The './tmp' folder should be empty after importation. 
If `temporary_directory` is removed then check ./tmp the temporary system folder will be used and will not contain any folder created current the process ( all folder will be deleted)

**Current behvior**
The './tmp' folder is not empty

**Comment by medamineziraoui** [comment]
For  files that are contained in default or custom temporary folder that do not disappear will be fixed on this issue https://github.com/saagie/gradle-saagie-dataops-plugin/issues/260

**Comment by sgokaram-saagie** [comment]
Looks like there is still issues on mac.  In the export directory it still creating these files. This was an old bug looks like resurfaced when libs where changed. 

saagies-mbp:job shivakumar$ ls -tlar
total 69288
-rw-r--r--   1 shivakumar  staff  35226861 Jun 22 13:09 export.zip
-rw-r--r--   1 shivakumar  staff      2456 Jul  1 11:07 19228.zip
-rw-r--r--   1 shivakumar  staff         0 Jul 13 16:26 .!22769!21754.zip
-rw-r--r--   1 shivakumar  staff         0 Jul 13 16:26 .!70129!19228.zip
-rw-r--r--   1 shivakumar  staff         0 Jul 13 16:26 .!22176!python.zip
-rw-r--r--   1 shivakumar  staff         0 Jul 13 16:26 .!22168!talend.zip
-rw-r--r--   1 shivakumar  staff         0 Jul 13 16:26 .!22171!export.zip
-rw-r--r--   1 shivakumar  staff         5 Jul 13 16:26 .!82966!r.zip
-rw-r--r--   1 shivakumar  staff         5 Jul 13 16:26 .!81652!spark.zip
-rw-r--r--   1 shivakumar  staff         0 Jul 13 16:26 .!81655!sqoop.zip
-rw-r--r--   1 shivakumar  staff         5 Jul 13 16:26 .!81654!java.zip
-rw-r--r--   1 shivakumar  staff         0 Jul 13 16:26 .!22167!19228.zip
-rw-r--r--   1 shivakumar  staff         0 Jul 13 16:26 .!22173!sqoop.zip
-rw-r--r--   1 shivakumar  staff         0 Jul 13 16:26 .!70130!export.zip
-rw-r--r--   1 shivakumar  staff         0 Jul 13 16:26 .!76383!export.zip
-rw-r--r--   1 shivakumar  staff         5 Jul 13 16:26 .!82974!19228.zip
-rw-r--r--   1 shivakumar  staff         5 Jul 13 16:26 .!81650!19228.zip
-rw-r--r--   1 shivakumar  staff         5 Jul 13 16:26 .!82976!talend.zip
-rw-r--r--   1 shivakumar  staff         5 Jul 13 16:26 .!82977!spark.zip
-rw-r--r--   1 shivakumar  staff         0 Jul 13 16:26 .!81651!talend.zip
-rw-r--r--   1 shivakumar  staff         0 Jul 13 16:26 .!82979!export.zip
-rw-r--r--   1 shivakumar  staff         5 Jul 13 16:26 .!81645!r.zip
-rw-r--r--   1 shivakumar  staff         5 Jul 13 16:26 .!82981!java.zip
-rw-r--r--   1 shivakumar  staff         5 Jul 13 16:26 .!82982!sqoop.zip
-rw-r--r--   1 shivakumar  staff         0 Jul 13 16:26 .!76382!19228.zip
-rw-r--r--   1 shivakumar  staff         0 Jul 13 16:26 .!22169!spark.zip
-rw-r--r--   1 shivakumar  staff         0 Jul 13 16:26 .!22172!java.zip
-rw-r--r--   1 shivakumar  staff         5 Jul 13 16:26 .!81659!docker.zip
-rw-r--r--   1 shivakumar  staff         0 Jul 13 16:26 .!81653!export.zip
-rw-r--r--   1 shivakumar  staff         5 Jul 13 16:26 .!81663!python.zip
-rw-r--r--   1 shivakumar  staff         5 Jul 13 16:26 .!82989!docker.zip
-rw-r--r--   1 shivakumar  staff         5 Jul 13 16:26 .!82990!python.zip
-rw-r--r--   1 shivakumar  staff         0 Jul 13 16:26 .!22163!r.zip
-rw-r--r--   1 shivakumar  staff         0 Jul 13 16:26 .!22175!docker.zip
-rw-r--r--   1 shivakumar  staff       654 Jul 14 09:18 docker.zip
-rw-r--r--   1 shivakumar  staff      1064 Jul 14 09:19 python.zip
-rw-r--r--   1 shivakumar  staff       982 Jul 14 09:19 r.zip
-rw-r--r--   1 shivakumar  staff      2351 Jul 14 09:19 spark.zip
-rw-r--r--   1 shivakumar  staff       651 Jul 14 09:19 sqoop.zip
-rw-r--r--   1 shivakumar  staff      1047 Jul 14 09:19 talend.zip
drwxr-xr-x  43 shivakumar  staff      1376 Jul 17 14:19 .
-rw-r--r--   1 shivakumar  staff      2514 Jul 17 14:19 java.zip
drwxr-xr-x  56 shivakumar  staff      1792 Jul 17 14:23 ..
