### ISSUE TITLE
Export / Import Versions - Descriptive Output for number of versions

### ISSUE THREAD

**Issue by sgokaram-saagie** [saagie/gradle-saagie-dataops-plugin#257]
Currenly the output of the export and import task does not describe if there are more than 1 version being exported or imported. 

For eg: The Sample spark job 4708 has 7 versions. The output is as below 

> Task :projectExportSpark
equals(o) triggered
equals(o) triggered
equals(o) triggered
equals(o) triggered
equals(o) triggered
equals(o) triggered
equals(o) triggered
equals(o) triggered
equals(o) triggered
equals(o) triggered
equals(o) triggered
equals(o) triggered
{"status":"success","exportfile":"./job/spark.zip"}

> Task :projectImportSpark
{status=success, job=[{id=4708, name=pm Extraction batch PLCs}], pipeline=[]}

There is no indication that it exported and imported 3 versions .

**Comment by medamineziraoui** [comment]
we will just indicate the quantity of versions exported ?
like so
job=[{id=4708, name=pm Extraction batch PLCs, versions=3}]

**Comment by sgokaram-saagie** [comment]
ok thats fine

**Comment by medamineziraoui** [comment]
**How to test :**

Version to test : **2.0.28**

**The Export phase:**

We going to call this process Export/Import-job

Create a build file:
**Example of** `build.projectsExportV1.gradle`:

```
plugins {
  id "io.saagie.gradle-saagie-dataops-plugin" version "2.0.28"
}
saagie {
    server {
        url = "REPLACE_SAAGIEURL"
        login = "REPLACE_SAAGIELOGIN"
	password = "REPLACE_SAAGIEPASSWORD"
        environment = "REPLACE_SAAGIE"
	jwt = true
    }
    job {
          ids =  [ "4708" ]
          include_all_versions = true
        }
    exportArtifacts {
          export_file = "./job/export.zip" // <=== url "./job/" should exist  
          overwrite=true
	  temporary_directory='./tmp'    // <=== temporary_directory ./tmp'  should exist        
    }
}
```
Export job using this commande :
**The command line** : `gradle -b build.projectsExportV1.gradle projectsExportV1`

**The import phase:** 

You should get
{"status":"success","exportfile":"./job/export.zip"}
Then use this command to export the job V1

Create a new build file:
**Example :** build.projectsImport.gradle:

```
plugins {
    id 'groovy'
    id 'io.saagie.gradle-saagie-dataops-plugin' version '2.0.28'
}

saagie {
    server {
        url = "REPLACE_SAAGIEURL"
        login = "REPLACE_SAAGIELOGIN"
	password = "REPLACE_SAAGIEPASSWORD"
        environment = "REPLACE_SAAGIE"
	jwt = true
        acceptSelfSigned = true
    }
    project {
        id = "REPLACE_SAAGIE_PROJECT_ID"
    }
    importArtifacts {
        import_file = "./job/export.zip"
        temporary_directory='./tmp'
    }
}
```
Then use this command line:
**The command line :** `gradle -b build.projectsImport.gradle projectsImport`

**Expected behvior**
You should get

```
> Task :projectsImport
{status=success, job=[{id=4708, name=pm Extraction batch PLCs, versions=7}], pipeline=[]}

BUILD SUCCESSFUL in 6s
1 actionable task: 1 executed

```
