### ISSUE TITLE
ProjectImport - Output for ERROR is not valid

### ISSUE THREAD

**Issue by sgokaram-saagie** [saagie/gradle-saagie-dataops-plugin#258]
Execute an import task with an invalid zip file. The out shows success

see below 

saagies-mbp:Gradle shivakumar$ gradle projectImportPipelineWithJobandVersion

> Task :projectImportPipelineWithJobandVersion
An error occurred when unzipping the artifacts export file.
{status=success, job=[], pipeline=[]}

BUILD SUCCESSFUL in 19s
2 actionable tasks: 2 executed

task projectImportPipelineWithJobandVersion( // <======== Import artifacts, see that we use the gradle dependOn
        type: ProjectsImportJobTask) {
    dependsOn(['projectExportPipelineWithJobandVersion'])
    configuration = saagie {
        server {
            url = saagieurl
            login = saagieuserid
            password = saagiepassword
            environment = saagieplatformid
            jwt = true
        }
    }
    doFirst {
        projectImportPipelineWithJobandVersion.configuration = saagie {
            project {
                id = saagieprojectid
            }
            importArtifacts {
                import_file = './pipeline/'
                temporary_directory= tmpLocation
            }
        }
    }
    description= 'Import Pipeline with Dependency Job and all versions'
    taskName = 'projectImportPipelineWithJobandVersion'
}

**Comment by medamineziraoui** [comment]
@sgokaram-saagie for the fixe. we will just remove the `{status=success, job=[], pipeline=[]}` part. we will just log 
Task :projectImportPipelineWithJobandVersion
An error occurred when unzipping the artifacts export file.
 Do you confirm?

**Comment by medamineziraoui** [comment]
**How to test :**

Version to test : **2.0.25**

**The Import phase:**
we need to import ths invalide zip file
[20994.zip](https://github.com/saagie/gradle-saagie-dataops-plugin/files/4954594/20994.zip)

Create a build file:
**Example of** `build.projectsImport.gradle`:

```
plugins {
    id 'groovy'
    id 'io.saagie.gradle-saagie-dataops-plugin' version '2.0.25'
}

saagie {
    server {
        url = saagieurl
        login = saagieuserid
        password = saagiepassword
        environment = saagieplatformid
        jwt = true
        acceptSelfSigned = true
    }

    project {
        id = saagieProject
    }

    importArtifacts {
        import_file = "/import/path/must/exist/20994.zip"
        temporary_directory='/import/path/must/exist/tmp'
    }
}

```
Export job using this commande :
**The command line** : `gradle -b build.projectsImport.gradle projectsImport`

You should get
```
> Task :projectsImport FAILED
An error occurred when unzipping the artifacts export file.
FAILURE: Build failed with an exception.

```
