### ISSUE TITLE
Temporary location is not cleaned up for error

### ISSUE THREAD

**Issue by sgokaram-saagie** [saagie/gradle-saagie-dataops-plugin#260]
If a task fails then the data is left behind in temporary location. 

Simulate an error for import pipeline , the task fails but when checking the temp location the files are still present. 

saagies-mbp:Gradle shivakumar$ gradle projectImportPipelineWithJobandVersion

> Task :projectExportPipelineWithJobandVersion
{"status":"success","exportfile":"./pipeline/pipelinejobver.zip"}

> Task :projectImportPipelineWithJobandVersion FAILED
Something went wrong when adding new job version: {"errors":[{"message":"Unexpected error"}],"data":null}

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':projectImportPipelineWithJobandVersion'.
> Something went wrong when adding new job version: {"errors":[{"message":"Unexpected error"}],"data":null}

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 37s
2 actionable tasks: 2 executed
saagies-mbp:Gradle shivakumar$ cd tmp/
saagies-mbp:tmp shivakumar$ ls
artifacts-59287231-63d5-4ae4-9dcb-775a36d01e15
saagies-mbp:tmp shivakumar$ ls -ltar
total 0
drwxr-xr-x  56 shivakumar  staff  1792 Jul 14 09:33 ..
drwxr-xr-x   3 shivakumar  staff    96 Jul 14 09:59 .
drwxr-xr-x   3 shivakumar  staff    96 Jul 14 09:59 artifacts-59287231-63d5-4ae4-9dcb-775a36d01e15
saagies-mbp:tmp shivakumar$ cd artifacts-59287231-63d5-4ae4-9dcb-775a36d01e15/
saagies-mbp:artifacts-59287231-63d5-4ae4-9dcb-775a36d01e15 shivakumar$ ls
pipelinejobver
saagies-mbp:artifacts-59287231-63d5-4ae4-9dcb-775a36d01e15 shivakumar$ cd pipelinejobver/
saagies-mbp:pipelinejobver shivakumar$ ls
Job		Pipeline
saagies-mbp:pipelinejobver shivakumar$ cd Pipeline/
saagies-mbp:Pipeline shivakumar$ ls
484
saagies-mbp:Pipeline shivakumar$ cd 484
saagies-mbp:484 shivakumar$ ls
pipeline.json

**Comment by medamineziraoui** [comment]
**How to test :**

Version to test : **2.0.25**

**The Import phase:**
we need to import ths invalide zip file
[20994.zip](https://github.com/saagie/gradle-saagie-dataops-plugin/files/4954594/20994.zip)

Create a build file:
**Example of** `build.projectsImport.gradle`:

```
plugins {
    id 'groovy'
    id 'io.saagie.gradle-saagie-dataops-plugin' version '2.0.25'
}

saagie {
    server {
        url = saagieurl
        login = saagieuserid
        password = saagiepassword
        environment = saagieplatformid
        jwt = true
        acceptSelfSigned = true
    }

    project {
        id = saagieProject
    }

    importArtifacts {
        import_file = "/import/path/must/exist/20994.zip"
        temporary_directory='/import/path/must/exist/tmp' <===== you need to empty this path before you test
    }
}

```
Export job using this commande :
**The command line** : `gradle -b build.projectsImport.gradle projectsImport`

You should get
```
> Task :projectsImport FAILED
An error occurred when unzipping the artifacts export file.
FAILURE: Build failed with an exception.
```
Then check the '/import/path/must/exist/tmp' path, if it s emty then this issue is ok.
