### ISSUE TITLE
Error while migrating project from A4 to OVH

### ISSUE THREAD

**Issue by tquiviger** [saagie/gradle-saagie-dataops-plugin#335]
When trying to migrate projects from A4 to OVH I'm facing issues during the import phase.

```
Something went wrong when creating project job: {"errors":[{"message":"Job not valid","extensions":{"technology":"not exists","commandLine":"not allowed","package":"not allowed","classification":"ValidationError"}}],"data":null}
```

Both source and target platforms have the latest Saagie version (with Catalog). Zip file included for you to check.

[7024406c.zip](https://github.com/saagie/gradle-saagie-dataops-plugin/files/5339089/7024406c.zip)

**Comment by tquiviger** [comment]
Command used :
```
gradle projectsImport -PprojectSaagie="583dc9a5-35f7-4bcd-adc0-198cd798f952" -Pimportpath="2d45dd2e"
```

build.gradle : 

```
plugins {
  id "io.saagie.gradle-saagie-dataops-plugin" version "2.1.12"
}

saagie {
     server {
        url = "https://datafabric-workspace.bva.saagie.io"
        login = "thomas.quiviger"
        password = "xxxxxxxxx"
        environment = 1
        jwt = true
        timeout = 3
    }

    project {
      id = projectSaagie
      include_all_artifacts=true
    }

    importArtifacts {
          import_file ="./exports/${importpath}.zip"  
    }
}
```

**Comment by ZouhairBear** [comment]
**How to test :**

Version to test : **2.1.12**

**The Export phase:**

Create a build file:
**Example of** `build.projectsExport.gradle`:

```
plugins {
  id "io.saagie.gradle-saagie-dataops-plugin" version "2.1.12"
}
saagie {
    server {
        url = "REPLACE_SAAGIEURL"
        login = "REPLACE_SAAGIELOGIN"
	password = "REPLACE_SAAGIEPASSWORD"
        environment = "REPLACE_SAAGIE"
	jwt = true
    }
    project {
        id = "REPLACE_SAAGIE_PROJECT_ID"
        include_all_artifacts=true
    }
    
    exportArtifacts {
          export_file = "./job/bash.zip" // <=== url "./job/" should exist  
          overwrite=true  // <=== temporary_directory ./tmp'  should exist        
    }
}
```

Export job using this commande :
**The command line** : `gradle -b build.projectsExport.gradle projectsExport`


**The import phase:** 

Create a new build file:
**Example :** build.projectsImport.gradle:

```
plugins {
    id 'groovy'
    id 'io.saagie.gradle-saagie-dataops-plugin' version '2.1.1é'
}

saagie {
    server {
        url = "REPLACE_SAAGIEURL"
        login = "REPLACE_SAAGIELOGIN"
	password = "REPLACE_SAAGIEPASSWORD"
        environment = "REPLACE_SAAGIE"
	jwt = true
        acceptSelfSigned = true
    }
    project {
        id = "REPLACE_SAAGIE_PROJECT_ID"
    }
    importArtifacts {
        import_file = "./job/export.zip"
        temporary_directory='./tmp'
    }
}
```
Then use this command line:
**The command line :** `gradle -b build.projectsImport.gradle projectsImport`


**Expected behvior**

```
> Task :projectsImport
{status=success, job=[{id=job_id_v2, name=bash job name}], pipeline=[]}

BUILD SUCCESSFUL in 5s
1 actionable task: 1 executed

```

**Comment by ZouhairBear** [comment]
- # I have tested export Job from V2 with plugin version 2.1.12 : it works as expected
![335-export](https://user-images.githubusercontent.com/60467819/95581983-3811be80-0a3a-11eb-98cf-ca7f16c45ae7.gif)

- # I have tested import Job from V2 with plugin version 2.1.12 : it works as expected

![335-import](https://user-images.githubusercontent.com/60467819/95581994-4069f980-0a3a-11eb-902a-3251e8c7a5bd.gif)
![335-import-2](https://user-images.githubusercontent.com/60467819/95582010-44961700-0a3a-11eb-9ef9-7a14b0a5713b.gif)

**Comment by ZouhairBear** [comment]
**How to test :**

Version to test : **2.1.16**

**The Export phase:**

Create a build file:
**Example of** `build.projectsExport.gradle`:

```
plugins {
  id "io.saagie.gradle-saagie-dataops-plugin" version "2.1.12"
}
saagie {
    server {
        url = "REPLACE_SAAGIEURL"
        login = "REPLACE_SAAGIELOGIN"
	password = "REPLACE_SAAGIEPASSWORD"
        environment = "REPLACE_SAAGIE"
	jwt = true
    }
    project {
        id = "REPLACE_SAAGIE_PROJECT_ID"
        include_all_artifacts=true
    }
    
    exportArtifacts {
          export_file = "./job/bash.zip" // <=== url "./job/" should exist  
          overwrite=true  // <=== temporary_directory ./tmp'  should exist        
    }
}
```

Export job using this commande :
**The command line** : `gradle -b build.projectsExport.gradle projectsExport`


**The import phase:** 

Create a new build file:
**Example :** build.projectsImport.gradle:

```
plugins {
    id 'groovy'
    id 'io.saagie.gradle-saagie-dataops-plugin' version '2.1.16'
}

saagie {
    server {
        url = "REPLACE_SAAGIEURL"
        login = "REPLACE_SAAGIELOGIN"
	password = "REPLACE_SAAGIEPASSWORD"
        environment = "REPLACE_SAAGIE"
	jwt = true
        acceptSelfSigned = true
    }
    project {
        id = "REPLACE_SAAGIE_PROJECT_ID"
    }
    importArtifacts {
        import_file = "./job/export.zip"
        temporary_directory='./tmp'
    }
}
```
Then use this command line:
**The command line :** `gradle -b build.projectsImport.gradle projectsImport`


**Expected behvior**

```
> Task :projectsImport
{status=success, job=[{id=job_id_v2, name=bash job name}], pipeline=[]}

BUILD SUCCESSFUL in 5s
1 actionable task: 1 executed

```

**Comment by ZouhairBear** [comment]
- # I have tested export Job from V2 with plugin version 2.1.16 : it works as expected
![335-export-v16](https://user-images.githubusercontent.com/60467819/95583610-aeafbb80-0a3c-11eb-8567-738940ebd192.gif)

- # I have tested import Job from V2 with plugin version 2.1.16 : it works as expected
![335-import-v16](https://user-images.githubusercontent.com/60467819/95583621-b4a59c80-0a3c-11eb-8a3c-48f6ceb95e7b.gif)
![335-import-v16-2](https://user-images.githubusercontent.com/60467819/95583649-bc654100-0a3c-11eb-9927-d8447a7dbc67.gif)
