### ISSUE TITLE
Pipeline import - Jobs in the opposite order

### ISSUE THREAD

**Issue by tquiviger** [saagie/gradle-saagie-dataops-plugin#351]
When exporting a project and importing it to another platform, pipelines are imported correctly but jobs inside are in the opposite order
![image](https://user-images.githubusercontent.com/8511444/96101425-ba383200-0ed5-11eb-8ff8-9a928c079bfd.png)
![image](https://user-images.githubusercontent.com/8511444/96101444-befce600-0ed5-11eb-92a7-9403b217979e.png)

 id "io.saagie.gradle-saagie-dataops-plugin" version "2.1.12"

**Comment by ZouhairBear** [comment]
**How to test :**

Version to test : **2.1.17**

**The Export phase:**

Create a build file:
**Example of** `build.projectsExport.gradle`:

```
plugins {
  id "io.saagie.gradle-saagie-dataops-plugin" version "2.1.4"
}
saagie {
    server {
        url = "REPLACE_SAAGIEURL"
        login = "REPLACE_SAAGIELOGIN"
	password = "REPLACE_SAAGIEPASSWORD"
        environment = "REPLACE_SAAGIE"
	jwt = true
    }
    project {
        id = "REPLACE_SAAGIE_PROJECT_ID"
    }
    pipeline {
          ids =  [ "802040db-c2fe-4569-959c-75a6411cda6d" ] // <=== You need to make sure that this pipeline id exist in saagie platform
        }
    exportArtifacts {
          export_file = "./pipeline.zip" // <=== url  should exist  
          overwrite=true  // <=== temporary_directory ./tmp'  should exist        
    }
}
```

Export job using this commande :
**The command line** : `gradle -b build.projectsExport.gradle projectsExport`


**The import phase:** 

Create a new build file:
**Example :** build.projectsImport.gradle:

```
plugins {
    id 'groovy'
    id 'io.saagie.gradle-saagie-dataops-plugin' version '2.1.4'
}

saagie {
    server {
        url = "REPLACE_SAAGIEURL"
        login = "REPLACE_SAAGIELOGIN"
	password = "REPLACE_SAAGIEPASSWORD"
        environment = "REPLACE_SAAGIE"
	jwt = true
        acceptSelfSigned = true
    }
    project {
        id = "REPLACE_SAAGIE_PROJECT_ID"
    }
    importArtifacts {
        import_file = "./pipeline.zip"
        temporary_directory='./tmp'
    }
}
```
Then use this command line:
**The command line :** `gradle -b build.projectsImport.gradle projectsImport`

**Comment by ZouhairBear** [comment]
- # I have tested export pipeline  from V2 with the same order of jobs : it works as expected
![351-export](https://user-images.githubusercontent.com/60467819/96695378-df231e00-1389-11eb-818f-7999e23fb418.gif)
![351-export1](https://user-images.githubusercontent.com/60467819/96695391-e4806880-1389-11eb-9d43-77b02373f2dd.gif)
![351-export2](https://user-images.githubusercontent.com/60467819/96695408-e813ef80-1389-11eb-9f2a-9cfbdefca9f8.gif)
- # I have tested import pipeline  from V2 with the same order of jobs : it works as expected
![351-import](https://user-images.githubusercontent.com/60467819/96695489-01b53700-138a-11eb-8ebf-020d813b5d3c.gif)
![351-import1](https://user-images.githubusercontent.com/60467819/96695506-0548be00-138a-11eb-8d0e-6528629ab5d0.gif)
![image](https://user-images.githubusercontent.com/60467819/96695583-1a255180-138a-11eb-8e43-7fe2c9dd8420.png)
![image](https://user-images.githubusercontent.com/60467819/96695635-28736d80-138a-11eb-89df-3a9114e642e1.png)

**Comment by sgokaram-saagie** [comment]
Looks like the order is still not working.  The exact same Churn Model in GradlePluginTest i tried to export and imported into GradlePluginTest1 and you can see the difference between them. Check it out. 

Also i got a error with timeout when i tried to import that pipeline. 

saagies-mbp:Gradle shivakumar$ gradle -b build.gradle.projectImportPipeline projectImport
Configuration on demand is an incubating feature.

> Task :projectsImport FAILED
Unknown error in updatePipelineVersion
timeout
timeout

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':projectsImport'.
> java.net.SocketTimeoutException: timeout

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5m 27s
1 actionable task: 1 executed

**Comment by ZouhairBear** [comment]
I havec cheched the order of jobs of the pipeline `Churn Model in gradle` in GradlePluginTest and GradlePluginTest1 and **they are the same**. You can see the test in the below screens : 
![orderPipeline](https://user-images.githubusercontent.com/60467819/98516823-4afff480-226d-11eb-9376-036f9f756cd8.gif)

![image](https://user-images.githubusercontent.com/60467819/98516790-3d4a6f00-226d-11eb-8b93-3b3f3a70f4e0.png)

**Comment by ZouhairBear** [comment]
## Retest the issue 
**How to test :**

Version to test : **2.1.19**

**The Export phase:**

Create a build file:
**Example of** `build.projectsExport.gradle`:

```
plugins {
  id "io.saagie.gradle-saagie-dataops-plugin" version "2.1.19"
}
saagie {
    server {
        url = "REPLACE_SAAGIEURL"
        login = "REPLACE_SAAGIELOGIN"
	password = "REPLACE_SAAGIEPASSWORD"
        environment = "REPLACE_SAAGIE"
	jwt = true
    }
    project {
        id = "REPLACE_SAAGIE_PROJECT_ID"
        
    }
    pipeline {
          ids =  [ "802040db-c2fe-4569-959c-75a6411cda6d" ] // <=== You need to make sure that this pipeline id exist in saagie platform

       include_job=true
        include_all_versions=true
        }
    exportArtifacts {
          export_file = "./pipeline.zip" // <=== url  should exist  
          overwrite=true  // <=== temporary_directory ./tmp'  should exist        
    }
}
```

Export job using this commande :
**The command line** : `gradle -b build.projectsExport.gradle projectsExport`


**The import phase:** 

Create a new build file:
**Example :** build.projectsImport.gradle:

```
plugins {
    id 'groovy'
    id 'io.saagie.gradle-saagie-dataops-plugin' version '2.1.19'
}

saagie {
    server {
        url = "REPLACE_SAAGIEURL"
        login = "REPLACE_SAAGIELOGIN"
	password = "REPLACE_SAAGIEPASSWORD"
        environment = "REPLACE_SAAGIE"
	jwt = true
        acceptSelfSigned = true
    }
    project {
        id = "REPLACE_SAAGIE_PROJECT_ID"
    }
    importArtifacts {
        import_file = "./pipeline.zip"
        temporary_directory='./tmp'
    }
}
```
Then use this command line:
**The command line :** `gradle -b build.projectsImport.gradle projectsImport`

**Comment by ZouhairBear** [comment]
# Test the export phase : 
In this test, I have exported the pipeline `Churn Model` from project **gradle in GradlePluginTest**
![351-exportv19](https://user-images.githubusercontent.com/60467819/98521069-3fafc780-2273-11eb-9e28-383f85912011.gif)

**Comment by ZouhairBear** [comment]
# Test the export phase : 
In this test, I have import the pipeline `Churn Model` in project **projetc test issue 351**
- **File to import :** 
[Uploading 351_with_job.zip…]()
 
![351-importv19](https://user-images.githubusercontent.com/60467819/98521526-d67c8400-2273-11eb-8850-5660046eac92.gif)

**Comment by ZouhairBear** [comment]
- pipeline `Churn Update Model` from project **gradle in GradlePluginTest**

![image](https://user-images.githubusercontent.com/60467819/98521815-40952900-2274-11eb-9de0-cd10ae8a1d0d.png)

- pipeline `Churn Update Model` in project **projetc test issue 351**
![image](https://user-images.githubusercontent.com/60467819/98522136-9d90df00-2274-11eb-8b7e-22501b345ada.png)
