### ISSUE TITLE
Add projectsGetPipelineInstanceStatus

### ISSUE THREAD

**Issue by sgokaram-saagie** [saagie/gradle-saagie-dataops-plugin#41]
Accecptance Criteria

https://github.com/saagie/gradle-saagie-dataops-plugin/wiki/projectsGetPipelineInstanceStatus

**Comment by youenchene** [comment]
test not passing:

➜  test plugin gradle dataops gradle projectsGetPipelineInstanceStatus

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/youen/Code/saagie/test plugin gradle dataops/build.gradle' line: 23

* What went wrong:
A problem occurred evaluating root project 'test plugin gradle dataops'.
> Could not find method pipelineinstance() for arguments [build_5hztccp7vdj6lqhh0b85mrjce$_run_closure1$_closure5@3ebb0ebd] on object of type io.saagie.plugin.dataops.DataOpsExtension.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

    project {
        id = '2438b9b6-a9ee-4816-bfa8-9ed89896dfb4'
    }
        pipelineinstance {
          id = "17ea3ba9-d50a-4582-847d-648b39404e85"
        }
