### ISSUE TITLE
GetJobInstanceStatus - Does not work

### ISSUE THREAD

**Issue by sgokaram-saagie** [saagie/gradle-saagie-dataops-plugin#50]
Below Gradle file does not work. 

plugins {
  id "io.saagie.gradle-saagie-dataops-plugin" version "1.1.10"
}

saagie {
    server {
        url = 'https://saagie-beta.prod.saagie.io'
        login = saagieuserid
        password = saagiepassword
        environment = 4
        jwt = true
    }
    project {
        id = 'ec8c5cea-3dfd-4496-87a0-89f69101dccd'
    }
   jobinstance {
          id = '53b75b58-a136-499f-9370-f05abccb2a76'
   }
}

saagies-mbp:Gradle shivakumar$ gradle -b build.gradle.projectGetJobInstanceStatus projectsGetJobInstanceStatus

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/shivakumar/Documents/Demo/Gradle/build.gradle.projectGetJobInstanceStatus' line: 16

* What went wrong:
A problem occurred evaluating root project 'Gradle'.
> Could not find method jobinstance() for arguments [build_gradle_43uqvbeybn5e8ubjy1oo1vg2s$_run_closure1$_closure4@5e002c28] on object of type io.saagie.plugin.dataops.DataOpsExtension.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 462ms

**Comment by sgokaram-saagie** [comment]
@DecampsRenan  - Tested and this seems to work now.

**Comment by DecampsRenan** [comment]
Ok, I close the issue
