### ISSUE TITLE
Add projectsStopPipelineInstance

### ISSUE THREAD

**Issue by sgokaram-saagie** [saagie/gradle-saagie-dataops-plugin#54]
Acceptance Criteria

https://github.com/saagie/gradle-saagie-dataops-plugin/wiki/projectsStopPipelineInstance

**Comment by youenchene** [comment]
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/youen/Code/saagie/test plugin gradle dataops/build.gradle' line: 25

* What went wrong:
A problem occurred evaluating root project 'test plugin gradle dataops'.
> Could not find method pipelineinstance() for arguments [build_5hztccp7vdj6lqhh0b85mrjce$_run_closure1$_closure4@25ffb933] on object of type io.saagie.plugin.dataops.DataOpsExtension.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

  project {
        id = '2438b9b6-a9ee-4816-bfa8-9ed89896dfb4'
    }


        pipelineinstance {
          id = "e30fc9fe-3e89-4f7b-8ae0-7a73170d93da"
        }
