### ISSUE TITLE
Alerting mail addresses field name has changed

### ISSUE THREAD

**Issue by adrienblind** [saagie/gradle-saagie-dataops-plugin#63]
The signature of the Saagie v2 API has changed.

Previously, the projectCreateJob api required to set mail addresses for alerting purpose ; the field was named "mails".

Now, users must provide login names, their corresponding mail address will be gathered automatically. The field name has been changed from "mails" to "logins".

**Comment by youenchene** [comment]
Correct change to retrieve both "mails" and "logins".

**Comment by youenchene** [comment]
alerting parameters not taken in account :

  job {
       // id = '2e5cc738-1335-42a7-8fa9-011387f7b19b'
        name = 'Test Job 3'
        description = 'Description'
        technology = '13522063-c18b-4ecd-b61f-3bae1e0ad93c'
        category = 'Extraction'
        alerting {
            emails= ["y@saagie.com"]
            statusList= ["SUCCEEDED"]
          }
    }
   

    
     jobVersion {
      commandLine= "python {file} arg1 arg2"
      releaseNote = "Release corrigé"
      runtimeVersion = "3.6"
      packageInfo {
        name= "demo sk.py"
      }
     }


https://saagie-beta.prod.saagie.io/projects/platform/4/project/2438b9b6-a9ee-4816-bfa8-9ed89896dfb4/job/ca5b018a-5527-478b-9c78-022acdc83415
