### ISSUE TITLE
Duplicate Technologies in output of projectListTechnologies

### ISSUE THREAD

**Issue by sgokaram-saagie** [saagie/gradle-saagie-dataops-plugin#65]
if a project has same technology for Extranction and processing the list technologies displays them twice which is confusing. It does not state if this is for processing or extranction. 

Ideal solution is to just list it once and not display duplicate technologies. 

saagies-mbp:Gradle shivakumar$ gradle -b build.gradle.projectListTechnologies projectListTechnologies

> Task :projectsListTechnologies
[{"id":"13522063-c18b-4ecd-b61f-3bae1e0ad93c","label":"Python","isAvailable":true,"icon":"python","features":[]},{"id":"d18bdc90-6314-4718-9bcf-cd70df21273b","label":"Bash","isAvailable":true,"icon":"bash","features":[]},{"id":"d18bdc90-6314-4718-9bcf-cd70df21273b","label":"Bash","isAvailable":true,"icon":"bash","features":[]}]

BUILD SUCCESSFUL in 2s
1 actionable task: 1 executed

plugins {
  id "io.saagie.gradle-saagie-dataops-plugin" version "1.1.13"
}

saagie {
    server {
        url = saagieurl
        login = saagieuserid
        password = saagiepassword
        environment = saagieplatformid
        jwt = true
    }
    project {
        id = saagieprojectid
    }
}

The values of these variables are set in my gradle.settings.

**Comment by sgokaram-saagie** [comment]
@DecampsRenan  - Tested and this seems to work now

**Comment by DecampsRenan** [comment]
Ok, I'm going close the issue
