### ISSUE TITLE
projectsGetJobInstance does not work-Errors out

### ISSUE THREAD

**Issue by sgokaram-saagie** [saagie/gradle-saagie-dataops-plugin#67]
saagies-mbp:Gradle shivakumar$ gradle -b build.gradle.projectRunJob projectRunJob

> Task :projectsRunJob
plugins {
{"id":"5e060c51-dd16-4640-9741-d195757c00e7","status":"REQUESTED"}

BUILD SUCCESSFUL in 2s
1 actionable task: 1 executed
saagies-mbp:Gradle shivakumar$ vi build.gradle.projectGetJobInstanceStatus
saagies-mbp:Gradle shivakumar$ gradle -b build.gradle.projectGetJobInstanceStatus projectGetJobInstanceStatus

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/shivakumar/Documents/Demo/Gradle/build.gradle.projectGetJobInstanceStatus' line: 16

* What went wrong:
A problem occurred evaluating root project 'Gradle'.
> Could not find method jobinstance() for arguments [build_gradle_43uqvbeybn5e8ubjy1oo1vg2s$_run_closure1$_closure4@c07d07f] on object of type io.saagie.plugin.dataops.DataOpsExtension.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
plugins {

* Get more help at https://help.gradle.org

BUILD FAILED in 693ms

**Comment by DecampsRenan** [comment]
I think this issue is resolved with #80 so i close it
