### ISSUE TITLE
Provide Debug Option

### ISSUE THREAD

**Issue by sgokaram-saagie** [saagie/gradle-saagie-dataops-plugin#69]
We need to have a debug option for the plugin that can print additional information mainly the 
1. Request JSON used to invoke the API 
2. The Raw response received back from the API

**Comment by DecampsRenan** [comment]
I will use a built-in feature of gradle (https://docs.gradle.org/current/userguide/logging.html#sec:choosing_a_log_level); 
you will only need to add these options to enable the wanted log level.

Ex:
```sh
gradle projectsList -w # launch in warn mode
gradle projectsList -i # launch in info mode
gradle projectsList -d # launch in debug mode
```

**Comment by sgokaram-saagie** [comment]
ok . Thats perfect.
