### ISSUE TITLE
Plugin Compatibility with or with out API fix

### ISSUE THREAD

**Issue by sgokaram-saagie** [saagie/gradle-saagie-dataops-plugin#70]
There was a issue created in the API for email. The plugin seems like is not compatible and need to ensure it works if there is a fix applied or not the environment.

**Comment by youenchene** [comment]
Current dataops plugin version on last version of saagie : 

saagies-mbp:Gradle shivakumar$ gradle -b build.gradle.projectsCreateJob projectsCreateJob
Task :projectsCreateJob FAILED
Something went wrong when creating project job: {“errors”:[{“message”:“Job not valid”,“extensions”:{“emails”:“not empty”,“classification”:“ValidationError”}}],“data”:null}
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ‘:projectsCreateJob’.
Something went wrong when creating project job: {“errors”:[{“message”:“Job not valid”,“extensions”:{“emails”:“not empty”,“classification”:“ValidationErr


Looks like we are sending the alerting part when creating a job even if nothing is set on the gradle file part.
