### ISSUE TITLE
Project Update Job Fails 

### ISSUE THREAD

**Issue by sgokaram-saagie** [saagie/gradle-saagie-dataops-plugin#79]
saagies-mbp:Gradle shivakumar$ gradle -b build.gradle.projectsUpdateJob projectsUpdateJob
> Task :projectsUpdateJob FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':projectsUpdateJob'.
> Bad config. Make sure you provide rights params: https://github.com/saagie/gradle-saagie-dataops-plugin/wiki/projectsUpdateJob

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
1 actionable task: 1 executed

plugins {
  id "io.saagie.gradle-saagie-dataops-plugin" version "1.1.8"
}

saagie {
   server {
        url = saagieurl
        login = saagieuserid
        password = saagiepassword
        environment = saagieplatformid
        jwt = true
    }
    project {
        id = saagieprojectid
    }

    job {
          id = '66166ed1-3de4-4530-b83e-87f8fa633bb2'
    }

     jobVersion {
      commandLine= "python {file} arg1 arg2"
      releaseNote = "Release version updated"
      runtimeVersion = "2.7"
      packageInfo {
        name= "example.py"
      }
     }
}

The same used to work before.

**Comment by youenchene** [comment]
Still got an error 

   project {
        id = '2438b9b6-a9ee-4816-bfa8-9ed89896dfb4'
    }


    job {
        id = 'e098ec6c-dd87-4ce7-b243-bddbc6fd0fab'
        name = 'Test Job for the Boss 6'
        description = 'Description'
        //technology = '13522063-c18b-4ecd-b61f-3bae1e0ad93c'
        category = 'Extraction'
    }
     
     jobVersion {
      commandLine= "python {file} arg1 arg2"
      releaseNote = "Release corrigé"
      runtimeVersion = "3.6"
     }

**Comment by youenchene** [comment]
More tests :

Job settings works (alerting, description)

jobversion nor working (error, or say OK but no change)
