### ISSUE TITLE
GetJobInstance does not work any more

### ISSUE THREAD

**Issue by sgokaram-saagie** [saagie/gradle-saagie-dataops-plugin#80]
saagies-mbp:Gradle shivakumar$ gradle -b build.gradle.projectsGetJobInstanceStatus projectsGetJobInstanceStatus

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/shivakumar/Documents/Demo/Gradle/build.gradle.projectsGetJobInstanceStatus' line: 16

* What went wrong:
A problem occurred evaluating root project 'Gradle'.
> Could not find method jobinstance() for arguments [build_gradle_2lvd03ggq9020x5csk8q6phum$_run_closure1$_closure4@6b0d1a4] on object of type io.saagie.plugin.dataops.DataOpsExtension.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 515ms

plugins {
  id "io.saagie.gradle-saagie-dataops-plugin" version "1.1.23"
}

saagie {
    server {
        url = saagieurl
        login = saagieuserid
        password = saagiepassword
        environment = saagieplatformid
        jwt = true
    }
    project {
        id = saagieprojectid
    }
   jobinstance {
          id = '8ea798c9-e600-4417-a574-c55842c65801'
   }
}

**Comment by DecampsRenan** [comment]
@sgokaram-saagie  I just found the issue: i named the config key according to the graphql schema, `jobInstance`; or you are using `jobinstance` with a lower cased `i`

Should I update the code to reflect the wiki, or should we update the wiki to reflect the graphql API ?

**Comment by sgokaram-saagie** [comment]
@DecampsRenan  - So i checked wiki for what has been out naming convention. So far i dont see any use of mixed case. So lets make it uniform and not use mixed cases just all lower case through out the project. This way we are consistent. 

So change the code for now to make it jobinstance lower case i. 

Let me know if there are other places of mixed case , i could not find them.

**Comment by DecampsRenan** [comment]
This issue is fixed with the #50 , so I close it
