### ISSUE TITLE
ProjectCreatePipleLine fails with emails not empty error

### ISSUE THREAD

**Issue by sgokaram-saagie** [saagie/gradle-saagie-dataops-plugin#89]
saagies-MacBook-Pro:Gradle shivakumar$ gradle -b build.gradle.projectCreatePipeline projectCreatePipeline

> Task :projectsCreatePipeline FAILED
Something went wrong when creating the pipeline: {"errors":[{"message":"Pipeline not valid","extensions":{"emails":"not empty","classification":"ValidationError"}}],"data":null}

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':projectsCreatePipeline'.
> Something went wrong when creating the pipeline: {"errors":[{"message":"Pipeline not valid","extensions":{"emails":"not empty","classification":"ValidationError"}}],"data":null}

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
1 actionable task: 1 executed

**Comment by youenchene** [comment]
Notification is not asked so you should ask for notification in the API call :

project {
       id = ‘2438b9b6-a9ee-4816-bfa8-9ed89896dfb4’
   }
    pipeline {
         name = “test pipeline”
         description = “des”
         isScheduled = false
       }
   pipelineVersion {
     releaseNote = “v1”
     jobs = [“dff6ca03-9dc6-403a-895c-71f36484e3a6",“e098ec6c-dd87-4ce7-b243-bddbc6fd0fab”]
   }
